{
  "templates": [
    {
      "id": "general",
      "name": "General Enhancement",
      "description": "Improve the overall quality of the description",
      "template": "You are helping to enhance a description for a world-building project.

        Node Information:
        - Name: {node_name}
        - Labels: {labels}
        - Tags: {tags}
        
        Connected Nodes:
        {context}
        
        Current Description:
        {description}
        
        Please enhance this description by:
        1.  Adding more vivid details
        2.  Improving the writing style
        3.  Structure the description in logical paragraphs
        4.  If the Connected Nodes section above contains only *No connected 
            nodes available*, focus solely on enhancing this node based on its own description and metadata.
            Otherwise, ensure consistency with information from connected nodes while enhancing this description. 
        5.  Your response must be valid HTML with proper paragraph tags (<p>) for each paragraph.
        6.  Maintaining the original tone and factual information
        7.  Follow the provided custom instructions: {custom_instructions}
        
        Your task is to produce an improved version that maintains all existing information while making it more engaging and detailed."
    },
    {
      "id": "details",
      "name": "Add Details",
      "description": "Expand the description with additional details",
      "template": "You are helping to add more details to a description for a world-building project.

        Node Information:
        - Name: {node_name}
        - Labels: {labels}
        - Tags: {tags}
        
        Connected Nodes:
        {context}
        
        Current Description:
        {description}
        
        Please enhance this description by:
        1.  adding more sensory details, background information, and specific characteristics.
        2.  Focus on expanding the existing content rather than changing the style.
        3.  Maintain the original tone and all factual information.
        4.  If the Connected Nodes section above contains only *No connected 
            nodes available*, focus solely on enhancing this node based on its own description and metadata.
            Otherwise, ensure consistency with information from connected nodes while enhancing this description.
        5.  Your response must be valid HTML with proper paragraph tags (<p>) 
            for each paragraph.
        7.  Follow the provided custom instructions: {custom_instructions}
        "
    },
    {
      "id": "style",
      "name": "Improve Style",
      "description": "Refine the writing style while preserving content",
      "template": "You are helping to improve the writing style of a description for a world-building project.

        Node Information:
        - Name: {node_name}
        - Labels: {labels}
        - Tags: {tags}
        
        Current Description:
        {description}
        
        Please improve the writing style of this description while maintaining all factual information. Focus on:
        
        1. Improving flow and readability
        2. Using more vivid language
        3. Correct grammar and punctuation
        4. Your response must be valid HTML with proper paragraph tags (<p>) for each paragraph.
        5. Maintaining consistency with the original tone
        7.  Follow the provided custom instructions: {custom_instructions}
        "

    },
    {
      "id": "quick",
      "name": "Quick Enhancement",
      "description": "Fast improvement with minimal configuration",
      "template": "You are helping to enhance a description for a world-building project.

        Node Information:
        - Name: {node_name}
        - Labels: {labels}
        - Tags: {tags}
        
        Connected Nodes:
        {context}
        
        Current Description:
        {description}
        
        Please enhance this description by:
        1.  Adding more vivid details while keeping it concise
        2.  Stick to the current description length, a minimum of 40 words
        2.  Improving the writing style for better flow
        3.  Structure the description in logical paragraphs
        4.  If the Connected Nodes section above contains only *No connected 
            nodes available*, focus solely on enhancing this node based on its own description and metadata.
            Otherwise, ensure consistency with information from connected nodes while enhancing this description.
        5.  Your response must be valid HTML with proper paragraph tags (<p>) 
            for each paragraph.
        6.  Maintaining the original tone and factual information
        7.  Follow the provided custom instructions: {custom_instructions}
        
        Focus on making quick, meaningful improvements without changing the core information."
    },
    {
      "id": "physical",
      "name": "Create Physical Description",
      "description": "Generate a physical description of a character, object,
       or place based on the provided information",
      "template": "You are helping to create a physical description for a world-building project.

        Node Information:
        - Name: {node_name}
        - Labels: {labels}
        - Tags: {tags}

        Connected Nodes:
        {context}

        Current Description:
        {description}

        Please create a physical description by:
        1.  Adding more vivid details while keeping it concise
        2.  Make the physical description in 80 words or less
        3.  Optimize the physical description to be processed by a text-to-image AI
        4.  If the Connected Nodes section above contains only *No connected 
            nodes available*, focus solely on enhancing this node based on its own description and metadata.
            Otherwise, ensure consistency with information from connected 
            nodes while creating the physical description.
        5.  Your response must be valid HTML with proper paragraph tags (<p>) 
            for each paragraph.
        6.  Follow the provided custom instructions: {custom_instructions}

        Focus on making quick, meaningful improvements without changing the core information."
    }
  ]
}